### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by simon88** [BertoldVdb/go-battgo#1]
Hi,
First of all thanks for you works this is amzing! I'am working with your library, so I have a question I have an USB to TTL and I want to use use it for my test. But I have a doubt about wiring my USB to my batterie. So I connect Tx ans Rx on my USB TTL together with a resistor (value 10k?), after thaht I plug this to Lin on my batterie am I right? But on my USB TTL I have also 5v and gnd so gnd is plus to gnd battery but for 5v what I do?

**Comment by BertoldVdb** [comment]
You do not need to use the 5V, the battery has its own power.

So you connect RX and TX with a resistor of a few kilo-ohm (I forgot the value I used, 4.7k I think). You connect the RX pin to the BattGo wire and connect the grounds together. The battery positive is not used.

Some USB dongles have leds driven by the TX/RX pins directly, this overloads the battery output and there may be communication problems.

BTW: In a real application you need some protection for the UART line, otherwise if you connect the battery positive to your system first the USB->UART dongle will likely burn out. For the unprotected setup make sure to connect the ground first.

BTW2: The feature for changing the battery parameters was not tested more than once, I was only reading telemetry and not setting anything.

**Comment by simon88** [comment]
Ok nice thanks for you reply, I'll try it quickly thanks again :)

**Comment by BertoldVdb** [comment]
Since there is at least one person interested in this library I updated the readme with the schematic of the simple interface, as well as a screenshot of the expected output. Normally the diode is not needed and a simple resistor works, but this is what I used.

I also added two bugfixes that apparently were not pushed, so please update your local copy. I retested changing the battery configuration, it does work.

**Comment by simon88** [comment]
nice, very nice work ! Just a question, in the photo where you show the D1, the white wire (VCC to RXD) is equal to the resistor?

**Comment by BertoldVdb** [comment]
No, you would not need the white wire. Just replace the diode with the resistor.

**Comment by simon88** [comment]
Replace the diode? Wire shall be replace by resistor no?

**Comment by BertoldVdb** [comment]
![battgo](https://user-images.githubusercontent.com/6325657/129054976-0172fb7b-ac9f-475f-854e-88e77954e6e8.png)
 Edit: sorry, I misread what you meant. Yes, the white wire has a very small SMD resistor in series :)

**Comment by simon88** [comment]
Ok great so I'll just to do the same as this

![image](https://user-images.githubusercontent.com/1391365/129182634-a642848e-de33-49e1-9d7a-7900fcac6399.png)

just replace the diode by a resistor and removing the white wire and after that connecting USB RX to BattGo data line
